### ISSUE TITLE
tuto_fonctionnel_18

### ISSUE THREAD

**Issue by HS-157** [nokomprendo/tuto_fonctionnel#1]
Salut,

Archlinux ne supporte plus que le 64 bits :
- https://archlinux.fr/accueil/fin-du-support-i686

Mais il y a une version communautaire qui supporte toujours la version 32 bits :
- https://archlinux32.org/

Pour l’installation, tu peux mettre un lien vers le wiki francophone qui explique comment faire l’installation, il est très bien fait :
- https://wiki.archlinux.fr/Installation

Il y a la page du wiki francophone ou anglophone de pacman qui explique aussi la majorité des fonctionnalités de pacman, il y a aussi la page pacman Rosetta qui montre les commandes équivalentes pour les autres gestionnaires de paquet :
- https://wiki.archlinux.fr/Pacman
- https://wiki.archlinux.org/index.php/pacman
- https://wiki.archlinux.org/index.php/Pacman/Rosetta

Mettre un lien vers la page anglophone de PKGBUILD qui l’explique et la bonne façon de les faire :
- https://wiki.archlinux.org/index.php/PKGBUILD
- https://wiki.archlinux.org/index.php/Creating_packages

Il y a l’option ```-s``` / ```--syncdeps``` pour makepkg pour installer les dépendances manquant pour compiler le paquet :
- https://wiki.archlinux.org/index.php/Makepkg#Usage

Dire « dépôt AUR » est un pléonasme, car AUR veut dire *Arch User Repository*

**Comment by nokomprendo** [comment]
Salut
Merci pour tes commentaires. J'ai fait les corrections et ajouté les liens sur la page github. Pour le pléonasme "dépot AUR" tu as parfaitement raison mais je préfère laisser comme ça car je pense que c'est plus clair pour les gens qui ne connaissent pas ou non anglophone.
